import { Building, Floor, Zone } from '../src/types.ts';

export const INITIAL_BUILDING: Building = {
  id: 'bldg-apex-01',
  name: 'Apex Commercial Tower',
  address: '500 Tech Boulevard, Innovation District',
  totalFloors: 4,
  totalZones: 24,
  floors: [
    {
      id: 'floor-1',
      name: 'Floor 1 - Reception & Common Hub',
      level: 1,
      totalAreaSqM: 1200,
      zones: [
        {
          id: 'zone-101',
          floorId: 'floor-1',
          name: 'Main Lobby & Reception',
          type: 'office',
          areaSqM: 350,
          isCritical: false,
          targetTemp: 22.0,
          minComfortTemp: 20.0,
          maxComfortTemp: 25.5,
          minVentilationCfm: 800,
          currentPresence: 1,
          currentTemp: 22.4,
          currentHumidity: 48,
          currentHvacPower: 8.5,
          currentLightingPower: 2.2,
          currentEquipmentPower: 3.0,
          totalPower: 13.7,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
        {
          id: 'zone-102',
          floorId: 'floor-1',
          name: 'Atrium & Central Corridor',
          type: 'corridor',
          areaSqM: 250,
          isCritical: false,
          targetTemp: 22.5,
          minComfortTemp: 19.5,
          maxComfortTemp: 26.0,
          minVentilationCfm: 500,
          currentPresence: 1,
          currentTemp: 22.8,
          currentHumidity: 46,
          currentHvacPower: 4.2,
          currentLightingPower: 1.8,
          currentEquipmentPower: 0.5,
          totalPower: 6.5,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
        {
          id: 'zone-103',
          floorId: 'floor-1',
          name: 'Ground Floor Cafeteria & Pantry',
          type: 'pantry',
          areaSqM: 300,
          isCritical: false,
          targetTemp: 21.5,
          minComfortTemp: 20.0,
          maxComfortTemp: 25.0,
          minVentilationCfm: 1200,
          currentPresence: 1,
          currentTemp: 22.1,
          currentHumidity: 52,
          currentHvacPower: 9.0,
          currentLightingPower: 1.5,
          currentEquipmentPower: 8.2,
          totalPower: 18.7,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
        {
          id: 'zone-104',
          floorId: 'floor-1',
          name: 'Visitor Conference Suite 1A',
          type: 'meeting_room',
          areaSqM: 120,
          isCritical: false,
          targetTemp: 22.0,
          minComfortTemp: 20.0,
          maxComfortTemp: 25.5,
          minVentilationCfm: 450,
          currentPresence: 0,
          currentTemp: 21.8,
          currentHumidity: 45,
          currentHvacPower: 1.5,
          currentLightingPower: 0.2,
          currentEquipmentPower: 0.8,
          totalPower: 2.5,
          hvacMode: 'energy_saving',
          lightingMode: 'off',
          lastOccupiedAt: new Date(Date.now() - 3600000).toISOString(),
        },
        {
          id: 'zone-105',
          floorId: 'floor-1',
          name: 'Restrooms East Wing',
          type: 'bathroom',
          areaSqM: 80,
          isCritical: false,
          targetTemp: 22.0,
          minComfortTemp: 19.0,
          maxComfortTemp: 26.0,
          minVentilationCfm: 600,
          currentPresence: 0,
          currentTemp: 22.0,
          currentHumidity: 55,
          currentHvacPower: 1.8,
          currentLightingPower: 0.6,
          currentEquipmentPower: 0.3,
          totalPower: 2.7,
          hvacMode: 'normal',
          lightingMode: 'dimmed',
          lastOccupiedAt: new Date(Date.now() - 600000).toISOString(),
        },
        {
          id: 'zone-106',
          floorId: 'floor-1',
          name: 'Telecom & Security Hub',
          type: 'equipment_room',
          areaSqM: 100,
          isCritical: true,
          targetTemp: 20.0,
          minComfortTemp: 18.0,
          maxComfortTemp: 23.0,
          minVentilationCfm: 800,
          currentPresence: 0,
          currentTemp: 20.2,
          currentHumidity: 42,
          currentHvacPower: 7.5,
          currentLightingPower: 0.3,
          currentEquipmentPower: 6.5,
          totalPower: 14.3,
          hvacMode: 'normal',
          lightingMode: 'dimmed',
          lastOccupiedAt: new Date(Date.now() - 7200000).toISOString(),
        },
      ],
    },
    {
      id: 'floor-2',
      name: 'Floor 2 - Engineering & Product',
      level: 2,
      totalAreaSqM: 1400,
      zones: [
        {
          id: 'zone-201',
          floorId: 'floor-2',
          name: 'Open Engineering Bay A',
          type: 'office',
          areaSqM: 400,
          isCritical: false,
          targetTemp: 22.0,
          minComfortTemp: 20.0,
          maxComfortTemp: 25.5,
          minVentilationCfm: 1400,
          currentPresence: 1,
          currentTemp: 22.6,
          currentHumidity: 49,
          currentHvacPower: 11.2,
          currentLightingPower: 2.8,
          currentEquipmentPower: 8.5,
          totalPower: 22.5,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
        {
          id: 'zone-202',
          floorId: 'floor-2',
          name: 'Open Engineering Bay B',
          type: 'office',
          areaSqM: 400,
          isCritical: false,
          targetTemp: 22.0,
          minComfortTemp: 20.0,
          maxComfortTemp: 25.5,
          minVentilationCfm: 1400,
          currentPresence: 1,
          currentTemp: 22.4,
          currentHumidity: 47,
          currentHvacPower: 10.8,
          currentLightingPower: 2.7,
          currentEquipmentPower: 7.9,
          totalPower: 21.4,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
        {
          id: 'zone-203',
          floorId: 'floor-2',
          name: 'Large Tech Conference Room 2A',
          type: 'meeting_room',
          areaSqM: 180,
          isCritical: false,
          targetTemp: 21.5,
          minComfortTemp: 20.0,
          maxComfortTemp: 25.5,
          minVentilationCfm: 700,
          currentPresence: 0,
          currentTemp: 21.2,
          currentHumidity: 44,
          currentHvacPower: 8.5,
          currentLightingPower: 2.1,
          currentEquipmentPower: 1.5,
          totalPower: 12.1,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date(Date.now() - 5400000).toISOString(),
        },
        {
          id: 'zone-204',
          floorId: 'floor-2',
          name: 'Engineering Breakout & Pantry',
          type: 'pantry',
          areaSqM: 140,
          isCritical: false,
          targetTemp: 22.0,
          minComfortTemp: 20.0,
          maxComfortTemp: 25.5,
          minVentilationCfm: 600,
          currentPresence: 1,
          currentTemp: 22.8,
          currentHumidity: 50,
          currentHvacPower: 3.5,
          currentLightingPower: 0.9,
          currentEquipmentPower: 3.2,
          totalPower: 7.6,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
        {
          id: 'zone-205',
          floorId: 'floor-2',
          name: 'Circulation Corridor Floor 2',
          type: 'corridor',
          areaSqM: 200,
          isCritical: false,
          targetTemp: 23.0,
          minComfortTemp: 19.5,
          maxComfortTemp: 26.0,
          minVentilationCfm: 400,
          currentPresence: 1,
          currentTemp: 23.1,
          currentHumidity: 45,
          currentHvacPower: 2.8,
          currentLightingPower: 1.2,
          currentEquipmentPower: 0.2,
          totalPower: 4.2,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
        {
          id: 'zone-206',
          floorId: 'floor-2',
          name: 'Floor 2 Server & Hardware Lab',
          type: 'server_room',
          areaSqM: 80,
          isCritical: true,
          targetTemp: 19.5,
          minComfortTemp: 18.0,
          maxComfortTemp: 22.5,
          minVentilationCfm: 900,
          currentPresence: 0,
          currentTemp: 19.8,
          currentHumidity: 41,
          currentHvacPower: 14.2,
          currentLightingPower: 0.4,
          currentEquipmentPower: 18.5,
          totalPower: 33.1,
          hvacMode: 'normal',
          lightingMode: 'off',
          lastOccupiedAt: new Date(Date.now() - 14400000).toISOString(),
        },
      ],
    },
    {
      id: 'floor-3',
      name: 'Floor 3 - Marketing, Sales & HR',
      level: 3,
      totalAreaSqM: 1400,
      zones: [
        {
          id: 'zone-301',
          floorId: 'floor-3',
          name: 'Sales Open Floor East',
          type: 'office',
          areaSqM: 420,
          isCritical: false,
          targetTemp: 22.0,
          minComfortTemp: 20.0,
          maxComfortTemp: 25.5,
          minVentilationCfm: 1300,
          currentPresence: 1,
          currentTemp: 22.3,
          currentHumidity: 48,
          currentHvacPower: 9.8,
          currentLightingPower: 2.5,
          currentEquipmentPower: 6.2,
          totalPower: 18.5,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
        {
          id: 'zone-302',
          floorId: 'floor-3',
          name: 'Marketing Creative Zone West',
          type: 'office',
          areaSqM: 380,
          isCritical: false,
          targetTemp: 22.0,
          minComfortTemp: 20.0,
          maxComfortTemp: 25.5,
          minVentilationCfm: 1200,
          currentPresence: 1,
          currentTemp: 22.5,
          currentHumidity: 47,
          currentHvacPower: 9.2,
          currentLightingPower: 2.3,
          currentEquipmentPower: 5.8,
          totalPower: 17.3,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
        {
          id: 'zone-303',
          floorId: 'floor-3',
          name: 'Client Pitch Room 3B',
          type: 'meeting_room',
          areaSqM: 160,
          isCritical: false,
          targetTemp: 21.5,
          minComfortTemp: 20.0,
          maxComfortTemp: 25.5,
          minVentilationCfm: 600,
          currentPresence: 1,
          currentTemp: 22.0,
          currentHumidity: 46,
          currentHvacPower: 4.8,
          currentLightingPower: 1.6,
          currentEquipmentPower: 2.0,
          totalPower: 8.4,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
        {
          id: 'zone-304',
          floorId: 'floor-3',
          name: 'Floor 3 Pantry & Coffee Bar',
          type: 'pantry',
          areaSqM: 150,
          isCritical: false,
          targetTemp: 22.0,
          minComfortTemp: 20.0,
          maxComfortTemp: 25.5,
          minVentilationCfm: 700,
          currentPresence: 1,
          currentTemp: 22.7,
          currentHumidity: 51,
          currentHvacPower: 3.8,
          currentLightingPower: 1.1,
          currentEquipmentPower: 4.5,
          totalPower: 9.4,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
        {
          id: 'zone-305',
          floorId: 'floor-3',
          name: 'Restrooms & Wellness Pods',
          type: 'bathroom',
          areaSqM: 90,
          isCritical: false,
          targetTemp: 22.0,
          minComfortTemp: 19.0,
          maxComfortTemp: 26.0,
          minVentilationCfm: 500,
          currentPresence: 1,
          currentTemp: 22.2,
          currentHumidity: 53,
          currentHvacPower: 2.1,
          currentLightingPower: 0.7,
          currentEquipmentPower: 0.4,
          totalPower: 3.2,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
        {
          id: 'zone-306',
          floorId: 'floor-3',
          name: 'Central Gallery & Hallway',
          type: 'corridor',
          areaSqM: 200,
          isCritical: false,
          targetTemp: 23.0,
          minComfortTemp: 19.5,
          maxComfortTemp: 26.0,
          minVentilationCfm: 400,
          currentPresence: 1,
          currentTemp: 22.9,
          currentHumidity: 46,
          currentHvacPower: 2.6,
          currentLightingPower: 1.3,
          currentEquipmentPower: 0.2,
          totalPower: 4.1,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
      ],
    },
    {
      id: 'floor-4',
      name: 'Floor 4 - Executive Suite & Data Center',
      level: 4,
      totalAreaSqM: 1200,
      zones: [
        {
          id: 'zone-401',
          floorId: 'floor-4',
          name: 'Executive Boardroom',
          type: 'meeting_room',
          areaSqM: 220,
          isCritical: false,
          targetTemp: 21.0,
          minComfortTemp: 20.0,
          maxComfortTemp: 24.5,
          minVentilationCfm: 800,
          currentPresence: 0,
          currentTemp: 21.4,
          currentHumidity: 43,
          currentHvacPower: 7.2,
          currentLightingPower: 1.9,
          currentEquipmentPower: 2.1,
          totalPower: 11.2,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date(Date.now() - 7200000).toISOString(),
        },
        {
          id: 'zone-402',
          floorId: 'floor-4',
          name: 'Executive Offices North',
          type: 'office',
          areaSqM: 250,
          isCritical: false,
          targetTemp: 22.0,
          minComfortTemp: 20.0,
          maxComfortTemp: 25.0,
          minVentilationCfm: 800,
          currentPresence: 1,
          currentTemp: 22.1,
          currentHumidity: 45,
          currentHvacPower: 5.5,
          currentLightingPower: 1.4,
          currentEquipmentPower: 3.5,
          totalPower: 10.4,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
        {
          id: 'zone-403',
          floorId: 'floor-4',
          name: 'Executive Offices South',
          type: 'office',
          areaSqM: 250,
          isCritical: false,
          targetTemp: 22.0,
          minComfortTemp: 20.0,
          maxComfortTemp: 25.0,
          minVentilationCfm: 800,
          currentPresence: 0,
          currentTemp: 22.0,
          currentHumidity: 44,
          currentHvacPower: 1.2,
          currentLightingPower: 0.2,
          currentEquipmentPower: 1.1,
          totalPower: 2.5,
          hvacMode: 'energy_saving',
          lightingMode: 'off',
          lastOccupiedAt: new Date(Date.now() - 10800000).toISOString(),
        },
        {
          id: 'zone-404',
          floorId: 'floor-4',
          name: 'Executive Lounge & Pantry',
          type: 'pantry',
          areaSqM: 150,
          isCritical: false,
          targetTemp: 22.0,
          minComfortTemp: 20.0,
          maxComfortTemp: 25.5,
          minVentilationCfm: 600,
          currentPresence: 0,
          currentTemp: 22.3,
          currentHumidity: 46,
          currentHvacPower: 1.5,
          currentLightingPower: 0.3,
          currentEquipmentPower: 1.8,
          totalPower: 3.6,
          hvacMode: 'energy_saving',
          lightingMode: 'dimmed',
          lastOccupiedAt: new Date(Date.now() - 5400000).toISOString(),
        },
        {
          id: 'zone-405',
          floorId: 'floor-4',
          name: 'Main Enterprise Data Center',
          type: 'server_room',
          areaSqM: 200,
          isCritical: true,
          targetTemp: 19.0,
          minComfortTemp: 17.5,
          maxComfortTemp: 22.0,
          minVentilationCfm: 2500,
          currentPresence: 0,
          currentTemp: 19.2,
          currentHumidity: 39,
          currentHvacPower: 28.5,
          currentLightingPower: 0.5,
          currentEquipmentPower: 42.0,
          totalPower: 71.0,
          hvacMode: 'normal',
          lightingMode: 'dimmed',
          lastOccupiedAt: new Date(Date.now() - 86400000).toISOString(),
        },
        {
          id: 'zone-406',
          floorId: 'floor-4',
          name: 'Floor 4 Foyer & VIP Elevator Lobby',
          type: 'corridor',
          areaSqM: 140,
          isCritical: false,
          targetTemp: 22.5,
          minComfortTemp: 19.5,
          maxComfortTemp: 26.0,
          minVentilationCfm: 400,
          currentPresence: 1,
          currentTemp: 22.4,
          currentHumidity: 45,
          currentHvacPower: 2.2,
          currentLightingPower: 1.0,
          currentEquipmentPower: 0.3,
          totalPower: 3.5,
          hvacMode: 'normal',
          lightingMode: 'on',
          lastOccupiedAt: new Date().toISOString(),
        },
      ],
    },
  ],
};
